---
- name: Lighthouse | Install git
  become: true
  yum:
    name: git
    state: present
- name: Lighhouse | Install nginx
  become: true
  yum:
    name: nginx
    state: present
- name: Lighthouse | Apply nginx config
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
- name: Lighthouse | Clone repository
  git:
    repo: "{{ lighthouse_url }}"
    dest: "{{ lighthouse_dir }}"
    version: master
- name: Lighthouse | Apply config
  become: true
  template:
    src: lighthouse_nginx.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: 0644
  notify: Nginx reload
